-- Novos campos em contacts
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS is_vip BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS zipcode TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS state TEXT;

-- Novos campos em campaigns
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS filter_gender TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS filter_vip BOOLEAN;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS filter_min_age INT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS filter_max_age INT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS filter_state TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS filter_city TEXT;